name: ios

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ios.yml'
      - 'quard_star_tools/**'

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/ios.yml'
      - 'quard_star_tools/**'

  workflow_dispatch:

jobs:
  quard_star_tools_ios_build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.2'
          modules: 'qt5compat'
          aqtversion: ==3.1.7

      - name: Install Qt ios
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.2'
          modules: 'qt5compat'
          aqtversion: ==3.1.7
          target: ios

      - name: Build all
        shell: bash -l {0}
        env:
          QT_VERSION: 6.5.2
        run: |
          cd quard_star_tools
          git describe --always --long --abbrev=10 --exclude '*' | awk '{print "\""$0"\""}' > git_tag.inc
          sed -i'.original' -e 's/git_tag.inc/git_tag.ci.inc/g' quard_star_tools.pro
          lrelease quard_star_tools.pro
          ${Qt6_DIR}/bin/qmake
          make
          cp -r ./Release-iphonesimulator/quard_star_tools.app ./         
          cp ./tools/convert-ipa.sh ./convert-ipa.sh
          ./convert-ipa.sh 
          mv ./IPAFolder/quard_star_tools.ipa ../

      - name: Upload build asserts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: quard_star_tools_ios
          path: |
            quard_star_tools.ipa
